"""reviews update

Revision ID: 741c5adeb9b8
Revises: 5aa8d1db0092
Create Date: 2025-08-17 16:11:43.082163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741c5adeb9b8'
down_revision = '5aa8d1db0092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_product_review', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_product_review', type_='unique')

    # ### end Alembic commands ###
