"""favorites update

Revision ID: 5aa8d1db0092
Revises: 86f7031fa621
Create Date: 2025-08-17 16:01:59.873789

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '5aa8d1db0092'
down_revision = '86f7031fa621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=SCHEMA) as batch_op:
    #with op.batch_alter_table('favorites') as batch_op:
        batch_op.create_unique_constraint('unique_user_product_fav', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=SCHEMA) as batch_op:
    #with op.batch_alter_table('favorites') as batch_op:
        batch_op.drop_constraint('unique_user_product_fav', type_='unique')

    # ### end Alembic commands ###
